services:
  - type: web
    name: pdfcrafter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn run:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0